-- =========================================
-- CUSTOMER ANALYSIS
-- =========================================


-- 1. Top 10 Customers by Total Spending
-- Identify the customers who generate the highest revenue.

SELECT
    o.customer_id,
    SUM(oi.quantity * oi.price) AS total_spending
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY o.customer_id
ORDER BY total_spending DESC
LIMIT 10;


-- 2. Number of Orders per Customer
-- Identify the customers with the highest number of orders.

SELECT
    o.customer_id,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM orders o
WHERE o.status = 'Completed'
GROUP BY o.customer_id
ORDER BY total_orders DESC
LIMIT 10;


-- 3. Revenue per Customer
-- Calculate total revenue generated by each customer.

SELECT
    o.customer_id,
    SUM(oi.quantity * oi.price) AS total_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY o.customer_id
ORDER BY total_revenue DESC
LIMIT 10;